### ISSUE TITLE
KeyError on import after installing with pip

### ISSUE THREAD

**Issue by mattmccormick** [salimfadhley/jenkinsapi#333]
After installing with pip (tried both versions 0.2.25 and 0.2.26) on Ubuntu 14.04, I get the following exception when trying to import jenkinsapi:

Exception Type: 	KeyError
Exception Value: 	'jenkinsapi'
Exception Location: 	/usr/local/lib/python2.7/dist-packages/jenkinsapi/__init__.py in <module>, line 69

This bug is also mentioned at http://stackoverflow.com/questions/26737107/import-python-module-fails

**Comment by mattmccormick** [comment]
Tried going backward in versions.  Installing 0.2.22 via pip worked as expected so this bug was introduced in 0.2.23

**Comment by salimfadhley** [comment]
Thanks for the bug report - I will look into this.

**Comment by salimfadhley** [comment]
Can you conform that you are using the latest versions of pip and
setuptools?

**Comment by mattmccormick** [comment]
pip list shows I am using:

pip (1.5.6)
setuptools (0.6c11)

**Comment by rocktavious** [comment]
Both pip and setuptools have been updated since(and changed their versioning scheme)

latest pip == 6.1.1  AKA  1.6.1.1
latest setuptools == 15.1  AKA  0.15.1

They changed their versioning scheme to be pep440 standard and show their longevity.  Latest versions of these packages work with latest jenkinsapi releases.  This bug should be closed.
